version: "3.9"

name: mvreels

services:
  db:
    image: postgres:16-alpine
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set-in-.env}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    # Optional to expose publicly
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--save",
        "60",
        "1000",
        "--requirepass",
        "${REDIS_PASSWORD:?set-in-.env}",
      ]
    volumes:
      - redis_data:/data
    # Optional
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile.prod
      target: runner
      args:
        NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-/api}
        API_BASE_INTERNAL: ${API_BASE_INTERNAL:-http://be:8080}
    container_name: next-web
    restart: unless-stopped
    env_file: .env
    environment:
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-/api}
      API_BASE_INTERNAL: ${API_BASE_INTERNAL:-http://be:8080}
    depends_on:
      - be
    expose:
      - "3000"

  be:
    build:
      context: ./be
      dockerfile: Dockerfile.prod
      target: prod
    container_name: nest-api
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: 8080
    depends_on:
      - db
      - redis
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: mvreels-nginx
    restart: unless-stopped
    depends_on:
      - fe
      - be
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "85:85"

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.test}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  redis_data:
  pgadmin_data:
